[package]
name = "eytzinger-layout"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false

[features]
prefetch = []
